import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/component/Header'
import Banner from '@/component/Banner'
import Package from '@/component/Package'
import Help from '@/component/Help'
import Future from '@/component/Future'
import Blue from '@/component/Blue'
import Question from '@/component/Question'
import Client from '@/component/Client'
import Footer from '@/component/Footer'
import Run from '@/component/Run'
import Map from '@/component/Map'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <main>
        <Header />
        <Banner />
        <Package />
        <Help />
        <Client />
        <Future />
        <Question />
        <Blue />
        <Map />
        <Footer />
        <Run />
      </main>
    </>
  )
}
